In [328]:
import pandas as pd

In [329]:
data=pd.read_csv("COVIDistress_data_with_region.csv",engine='python')
data['Country Income Level']=data['Country Income Level'].replace(['Low income'],'Low Income').replace(['High income'],'High Income')

In [330]:
data.head(2)

,ID,answered_all,Duration..in.seconds.,RecordedDate,UserLanguage,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Country Income Level,Region,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Dem_isolation,Dem_isolation_adults,Dem_isolation_kids,AD_gain,AD_loss,AD_check,Scale_PSS10_UCLA_1,Scale_PSS10_UCLA_2,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_4,Scale_PSS10_UCLA_5,Scale_PSS10_UCLA_6,Scale_PSS10_UCLA_7,Scale_PSS10_UCLA_8,Scale_PSS10_UCLA_9,Scale_PSS10_UCLA_10,Scale_SLON_1,Scale_SLON_2,Scale_SLON_3,OECD_people_1,OECD_people_2,OECD_insititutions_1,OECD_insititutions_2,OECD_insititutions_3,OECD_insititutions_4,OECD_insititutions_5,OECD_insititutions_6,Corona_concerns_1,Corona_concerns_2,Corona_concerns_3,Corona_concerns_4,Corona_concerns_5,Trust_countrymeasure,Compliance_1,Compliance_2,Compliance_3,Compliance_4,Compliance_5,Compliance_6,born_92,experience_war,experience_war_TXT,war_injury,loss_during_war,time_spent_in_war,time_spent_in_war_TXT,Scale_UCLA_TRI_1,Scale_UCLA_TRI_2,Scale_UCLA_TRI_3,Scale_UCLA_TRI_4,PS_PTSD_1,PS_PTSD_2,PS_PTSD_3,PS_PTSD_4,PS_PTSD_5,BFF_15_1,BFF_15_2,BFF_15_3,BFF_15_4,BFF_15_5,BFF_15_6,BFF_15_7,BFF_15_8,BFF_15_9,BFF_15_10,BFF_15_11,BFF_15_12,BFF_15_13,BFF_15_14,BFF_15_15,Expl_Distress_1,Expl_Distress_2,Expl_Distress_3,Expl_Distress_4,Expl_Distress_5,Expl_Distress_6,Expl_Distress_7,Expl_Distress_8,Expl_Distress_9,Expl_Distress_10,Expl_Distress_11,Expl_Distress_12,Expl_Distress_13,Expl_Distress_14,Expl_Distress_15,Expl_Distress_16,Expl_Distress_17,Expl_Distress_18,Expl_Distress_19,Expl_Distress_20,Expl_Distress_21,Expl_Distress_22,Expl_Distress_23,Expl_Distress_24,Expl_Distress_txt,SPS_1,SPS_2,SPS_3,SPS_4,SPS_5,SPS_6,SPS_7,SPS_8,SPS_9,SPS_10,Expl_Coping_1,Expl_Coping_2,Expl_Coping_3,Expl_Coping_4,Expl_Coping_5,Expl_Coping_6,Expl_Coping_7,Expl_Coping_8,Expl_Coping_9,Expl_Coping_10,Expl_Coping_11,Expl_Coping_12,Expl_Coping_13,Expl_Coping_14,Expl_Coping_15,Expl_Coping_16,Expl_coping_txt,Expl_media_1,Expl_media_2,Expl_media_3,Expl_media_4,Expl_media_5,Expl_media_6,Final_open,PSS10_avg,SLON3_avg,neu,ext,ope,agr,con,SPS_avg,Scale_UCLA_TRI_avg
0,4069,No,856,5/12/20 1:34,FA,30,Male,"College degree, bachelor, master",Up to 6 years of school,Full time employed,Afghanistan,Low Income,South Asia,yes,<U+06A9><U+0627><U+0628><U+0644>,Married/cohabiting,3.0,Yes,Life carries on with minor changes,4.0,0.0,NaN,Â· If Program D is adopted there is 1/3 probabi...,No,3.0,1.0,3.0,5.0,4.0,2.0,4.0,4.0,3.0,3.0,1.0,1.0,2.0,5.0,6.0,NaN,1.0,2.0,1.0,8.0,1.0,2.0,4.0,3.0,5.0,4.0,0.0,5.0,4.0,4.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,5.0,6.0,6.0,1.0,6.0,6.0,6.0,2.0,4.0,5.0,6.0,1.0,5.0,6.0,NaN,4.0,NaN,NaN,1.0,3.0,NaN,NaN,6.0,NaN,NaN,NaN,5.0,2.0,NaN,NaN,4.0,2.0,NaN,2.0,1.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2,1.333333,2.333333,6.0,6.0,4.666667,5.666667,NaN,NaN
1,4460,No,89,5/12/20 0:28,KO,26,Other/would rather not say,PhD/Doctorate,PhD/Doctorate,Student,Afghanistan,Low Income,South Asia,yes,<U+3147><U+314E>,Other or would rather not say,0.0,No,Life carries on as usual,0.0,0.0,NaN,Â· If Program C is adopted 400 people will die.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [331]:
data.groupby(["Region","Country"]).count().sort_values("ID",ascending=False)["ID"].to_frame()

                                                                   ID
Region                       Country
Europe and Central Asia      Finland                            22933
                             France                             13475
                             Denmark                            10891
Latin America and Caribbean  Mexico                              9169
Europe and Central Asia      Lithuania                           8255
Latin America and Caribbean  Argentina                           5923
East Asia and Pacific        Japan                               5072
Europe and Central Asia      Bulgaria                            4785
                             Poland                              3088
                             Sweden                              3055
                             Croatia                             2965
East Asia and Pacific        Taiwan                              2745
Europe and Central Asia      Kosovo                              2707
North America                United States                       2314
Europe and Central Asia      Czech Republic                      1995
                             Italy                               1749
East Asia and Pacific        Indonesia                           1569
Europe and Central Asia      United Kingdom                      1500
                             Germany                             1443
                             Hungary                             1438
                             Netherlands                         1433
                             Bosnia and Herzegovina              1288
                             Turkey                              1199
                             Switzerland                         1188
                             Portugal                            1067
                             Slovakia                             942
Latin America and Caribbean  Panama                               759
                             Brazil                               731
Europe and Central Asia      Greece                               642
                             Belgium                              622
                             Spain                                615
East Asia and Pacific        Philippines                          570
                             Malaysia                             567
                             Korea, South                         487
North America                Canada                               470
South Asia                   Bangladesh                           421
                             Pakistan                             360
East Asia and Pacific        Australia                            327
Europe and Central Asia      Austria                              319
                             Romania                              282
                             Serbia                               266
Other                        other                                223
Europe and Central Asia      Ireland                              216
Latin America and Caribbean  Colombia                             195
East Asia and Pacific        Vietnam                              173
Europe and Central Asia      Norway                               172
Sub-Saharan Africa           South Africa                         135
Europe and Central Asia      Russia                               132
East Asia and Pacific        New Zealand                          119
South Asia                   Afghanistan                          114
Europe and Central Asia      Albania                               79
Middle East and North Africa Egypt                                 74
East Asia and Pacific        China                                 74
Latin America and Caribbean  Chile                                 72
South Asia                   India                                 72
Europe and Central Asia      North Macedonia                       63
                             Luxembourg                            62
Middle East and North Africa United Arab Emirates                  56
Europe and Central Asia      Cyprus                                52
Middle East and North Africa Morocco                               44
Latin America and Caribbean  Peru                                  40
Europe and Central Asia      Estonia                               39
Middle East and North Africa Algeria                               38
Europe and Central Asia      Ukraine                               35
                             Kyrgyzstan                            35
Latin America and Caribbean  Guatemala                             35
                             Ecuador                               34
East Asia and Pacific        Singapore                             34
Latin America and Caribbean  Costa Rica                            26
                             Grenada                               25
Europe and Central Asia      Iceland                               25
Middle East and North Africa Israel                                24
Europe and Central Asia      Slovenia                              23
                             Latvia                                22
Middle East and North Africa Malta                                 22
Latin America and Caribbean  El Salvador                           20
Middle East and North Africa Qatar                                 20
East Asia and Pacific        Thailand                              19
Europe and Central Asia      Georgia                               19
Sub-Saharan Africa           Nigeria                               19
Middle East and North Africa Jordan                                18
Sub-Saharan Africa           Uganda                                17
Europe and Central Asia      Montenegro                            16
                             Azerbaijan                            15
                             Andorra                               15
Sub-Saharan Africa           Kenya                                 15
Europe and Central Asia      San Marino                            14
                             Belarus                               13
Middle East and North Africa Saudi Arabia                          13
Europe and Central Asia      Monaco                                12
Latin America and Caribbean  Honduras                              11
Sub-Saharan Africa           Angola                                11
Latin America and Caribbean  Venezuela                             11
Europe and Central Asia      Armenia                               10
Latin America and Caribbean  Nicaragua                             10
Middle East and North Africa Lebanon                               10
Sub-Saharan Africa           Lesotho                                9
                             Ghana                                  9
East Asia and Pacific        Brunei                                 8
Middle East and North Africa Iran                                   8
                             Tunisia                                8
                             Bahrain                                7
Latin America and Caribbean  Belize                                 7
South Asia                   Nepal                                  7
Latin America and Caribbean  Bolivia                                7
                             Trinidad and Tobago                    6
Sub-Saharan Africa           CÃ´te dâIvoire                          6
Europe and Central Asia      Liechtenstein                          5
Latin America and Caribbean  Antigua and Barbuda                    5
                             Uruguay                                5
East Asia and Pacific        Laos                                   5
                             Fiji                                   5
Sub-Saharan Africa           Gabon                                  5
                             Madagascar                             4
                             Zambia                                 4
South Asia                   Maldives                               4
Middle East and North Africa Oman                                   4
Sub-Saharan Africa           Burkina Faso                           4
                             Zimbabwe                               4
Latin America and Caribbean  Haiti                                  4
Middle East and North Africa Kuwait                                 4
Europe and Central Asia      Kazakhstan                             4
Middle East and North Africa Djibouti                               4
Latin America and Caribbean  Paraguay                               4
                             Dominican Republic                     4
                             Cuba                                   3
Europe and Central Asia      Moldova                                3
Latin America and Caribbean  Suriname                               3
Sub-Saharan Africa           Mauritius                              3
East Asia and Pacific        Micronesia, Federated States of        3
Sub-Saharan Africa           Cameroon                               3
                             Senegal                                3
South Asia                   Sri Lanka                              3
East Asia and Pacific        Cambodia                               3
Latin America and Caribbean  Barbados                               3
Sub-Saharan Africa           Congo, Republic of the                 2
                             Rwanda                                 2
                             Tanzania                               2
Europe and Central Asia      Uzbekistan                             2
Sub-Saharan Africa           Comoros                                2
                             Ethiopia                               2
                             Burundi                                2
Latin America and Caribbean  Jamaica                                2
Sub-Saharan Africa           Benin                                  2
East Asia and Pacific        Korea, North                           2
Latin America and Caribbean  The Bahamas                            2
Sub-Saharan Africa           Somalia                                1
                             Niger                                  1
East Asia and Pacific        Kiribati                               1
Sub-Saharan Africa           Sao Tome and Principe                  1
                             Seychelles                             1
                             Cabo Verde                             1
East Asia and Pacific        Myanmar (Burma)                        1
Sub-Saharan Africa           Namibia                                1
                             Sudan, South                           1
East Asia and Pacific        Nauru                                  1
Sub-Saharan Africa           The Gambia                             1
East Asia and Pacific        Solomon Islands                        1
Middle East and North Africa Iraq                                   1
Sub-Saharan Africa           Sudan                                  1
South Asia                   Bhutan                                 1
Sub-Saharan Africa           Mozambique                             1
                             Mauritania                             1
                             Mali                                   1
                             Malawi                                 1
Latin America and Caribbean  Dominica                               1
                             Saint Vincent and the Grenadines       1
                             Saint Lucia                            1
Sub-Saharan Africa           Guinea-Bissau                          1
                             Guinea                                 1
Europe and Central Asia      Turkmenistan                           1
Latin America and Caribbean  Guyana                                 1
Middle East and North Africa Libya                                  1
Sub-Saharan Africa           Eritrea                                1
East Asia and Pacific        East Timor (Timor-Leste)               1
Sub-Saharan Africa           Congo, Democratic Republic of the      1
Europe and Central Asia      Tajikistan                             1

In [332]:
data.sort_values(['Country Income Level']).groupby(["Region",'Country Income Level']).count()["ID"].to_frame()

                                                      ID
Region                       Country Income Level
East Asia and Pacific        High Income            5727
                             Low Income                2
                             Lower Middle Income    2326
                             Upper Middle Income    3732
Europe and Central Asia      High Income           80287
                             Low Income                9
                             Lower Middle Income     202
                             Upper Middle Income   10729
Latin America and Caribbean  High Income            1330
                             Lower Middle Income     457
                             Not Classified           11
                             Upper Middle Income   15322
Middle East and North Africa High Income             228
                             Lower Middle Income     108
                             Upper Middle Income      20
North America                High Income            2784
South Asia                   Low Income              114
                             Lower Middle Income     864
                             Upper Middle Income       4
Sub-Saharan Africa           High Income              20
                             Low Income               40
                             Lower Middle Income      81
                             Upper Middle Income     141

In [333]:
data.pivot_table(values='ID',columns='Country Income Level',index="Region",aggfunc= len)[["High Income","Upper Middle Income","Lower Middle Income","Low Income","Not Classified"]]

Country Income Level,High Income,Upper Middle Income,Lower Middle Income,Low Income,Not Classified
Region,,,,,
East Asia and Pacific,5727.0,3732.0,2326.0,2.0,NaN
Europe and Central Asia,80287.0,10729.0,202.0,9.0,NaN
Latin America and Caribbean,1330.0,15322.0,457.0,NaN,11.0
Middle East and North Africa,228.0,20.0,108.0,NaN,NaN
North America,2784.0,NaN,NaN,NaN,NaN
South Asia,NaN,4.0,864.0,114.0,NaN
Sub-Saharan Africa,20.0,141.0,81.0,40.0,NaN

In [334]:
data[["Country","Region",'Country Income Level']].loc[data['Country Income Level']=='Not Classified']

          Country                       Region Country Income Level
125114  Venezuela  Latin America and Caribbean       Not Classified
125115  Venezuela  Latin America and Caribbean       Not Classified
125116  Venezuela  Latin America and Caribbean       Not Classified
125117  Venezuela  Latin America and Caribbean       Not Classified
125118  Venezuela  Latin America and Caribbean       Not Classified
125119  Venezuela  Latin America and Caribbean       Not Classified
125120  Venezuela  Latin America and Caribbean       Not Classified
125121  Venezuela  Latin America and Caribbean       Not Classified
125122  Venezuela  Latin America and Caribbean       Not Classified
125123  Venezuela  Latin America and Caribbean       Not Classified
125124  Venezuela  Latin America and Caribbean       Not Classified

In [335]:
# From google: Venezuela, previously classified as an upper-middle income country, is now unclassified due to a lack of available data in the recent period.

In [336]:
data.head(2)

,ID,answered_all,Duration..in.seconds.,RecordedDate,UserLanguage,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Country Income Level,Region,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Dem_isolation,Dem_isolation_adults,Dem_isolation_kids,AD_gain,AD_loss,AD_check,Scale_PSS10_UCLA_1,Scale_PSS10_UCLA_2,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_4,Scale_PSS10_UCLA_5,Scale_PSS10_UCLA_6,Scale_PSS10_UCLA_7,Scale_PSS10_UCLA_8,Scale_PSS10_UCLA_9,Scale_PSS10_UCLA_10,Scale_SLON_1,Scale_SLON_2,Scale_SLON_3,OECD_people_1,OECD_people_2,OECD_insititutions_1,OECD_insititutions_2,OECD_insititutions_3,OECD_insititutions_4,OECD_insititutions_5,OECD_insititutions_6,Corona_concerns_1,Corona_concerns_2,Corona_concerns_3,Corona_concerns_4,Corona_concerns_5,Trust_countrymeasure,Compliance_1,Compliance_2,Compliance_3,Compliance_4,Compliance_5,Compliance_6,born_92,experience_war,experience_war_TXT,war_injury,loss_during_war,time_spent_in_war,time_spent_in_war_TXT,Scale_UCLA_TRI_1,Scale_UCLA_TRI_2,Scale_UCLA_TRI_3,Scale_UCLA_TRI_4,PS_PTSD_1,PS_PTSD_2,PS_PTSD_3,PS_PTSD_4,PS_PTSD_5,BFF_15_1,BFF_15_2,BFF_15_3,BFF_15_4,BFF_15_5,BFF_15_6,BFF_15_7,BFF_15_8,BFF_15_9,BFF_15_10,BFF_15_11,BFF_15_12,BFF_15_13,BFF_15_14,BFF_15_15,Expl_Distress_1,Expl_Distress_2,Expl_Distress_3,Expl_Distress_4,Expl_Distress_5,Expl_Distress_6,Expl_Distress_7,Expl_Distress_8,Expl_Distress_9,Expl_Distress_10,Expl_Distress_11,Expl_Distress_12,Expl_Distress_13,Expl_Distress_14,Expl_Distress_15,Expl_Distress_16,Expl_Distress_17,Expl_Distress_18,Expl_Distress_19,Expl_Distress_20,Expl_Distress_21,Expl_Distress_22,Expl_Distress_23,Expl_Distress_24,Expl_Distress_txt,SPS_1,SPS_2,SPS_3,SPS_4,SPS_5,SPS_6,SPS_7,SPS_8,SPS_9,SPS_10,Expl_Coping_1,Expl_Coping_2,Expl_Coping_3,Expl_Coping_4,Expl_Coping_5,Expl_Coping_6,Expl_Coping_7,Expl_Coping_8,Expl_Coping_9,Expl_Coping_10,Expl_Coping_11,Expl_Coping_12,Expl_Coping_13,Expl_Coping_14,Expl_Coping_15,Expl_Coping_16,Expl_coping_txt,Expl_media_1,Expl_media_2,Expl_media_3,Expl_media_4,Expl_media_5,Expl_media_6,Final_open,PSS10_avg,SLON3_avg,neu,ext,ope,agr,con,SPS_avg,Scale_UCLA_TRI_avg
0,4069,No,856,5/12/20 1:34,FA,30,Male,"College degree, bachelor, master",Up to 6 years of school,Full time employed,Afghanistan,Low Income,South Asia,yes,<U+06A9><U+0627><U+0628><U+0644>,Married/cohabiting,3.0,Yes,Life carries on with minor changes,4.0,0.0,NaN,Â· If Program D is adopted there is 1/3 probabi...,No,3.0,1.0,3.0,5.0,4.0,2.0,4.0,4.0,3.0,3.0,1.0,1.0,2.0,5.0,6.0,NaN,1.0,2.0,1.0,8.0,1.0,2.0,4.0,3.0,5.0,4.0,0.0,5.0,4.0,4.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,5.0,6.0,6.0,1.0,6.0,6.0,6.0,2.0,4.0,5.0,6.0,1.0,5.0,6.0,NaN,4.0,NaN,NaN,1.0,3.0,NaN,NaN,6.0,NaN,NaN,NaN,5.0,2.0,NaN,NaN,4.0,2.0,NaN,2.0,1.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2,1.333333,2.333333,6.0,6.0,4.666667,5.666667,NaN,NaN
1,4460,No,89,5/12/20 0:28,KO,26,Other/would rather not say,PhD/Doctorate,PhD/Doctorate,Student,Afghanistan,Low Income,South Asia,yes,<U+3147><U+314E>,Other or would rather not say,0.0,No,Life carries on as usual,0.0,0.0,NaN,Â· If Program C is adopted 400 people will die.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Creating Food Inscurity Data Frame - FI dataframe

In [344]:
FI=pd.read_csv("Country Food Insecurity.csv",header = 4)
FI.shape

(266, 65)

In [345]:
pd.set_option('display.max_columns', None)
FI.tail()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
261,Kosovo,XKX,Prevalence of moderate or severe food insecuri...,SN.ITK.MSFI.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,Prevalence of moderate or severe food insecuri...,SN.ITK.MSFI.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,Prevalence of moderate or severe food insecuri...,SN.ITK.MSFI.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.9,NaN,NaN,NaN,44.9,NaN
264,Zambia,ZMB,Prevalence of moderate or severe food insecuri...,SN.ITK.MSFI.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.8,49.4,50.1,50.8,51.4,NaN
265,Zimbabwe,ZWE,Prevalence of moderate or severe food insecuri...,SN.ITK.MSFI.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.7,66.7,67.0,66.7,69.8,NaN

In [346]:
FI.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')

In [347]:
FI['Indicator Name'].unique()

array(['Prevalence of moderate or severe food insecurity in the population (%)'],
      dtype=object)

In [348]:
FI['2020'].notnull().count()

266

In [349]:
FI = FI.filter(['Country Name','2019'], axis=1)
FI

                                          Country Name  2019
0                                                Aruba   NaN
1                          Africa Eastern and Southern   NaN
2                                          Afghanistan  63.1
3                           Africa Western and Central   NaN
4                                               Angola  73.5
5                                              Albania  33.8
6                                              Andorra   NaN
7                                           Arab World   NaN
8                                 United Arab Emirates   NaN
9                                            Argentina  35.8
10                                             Armenia  12.7
11                                      American Samoa   NaN
12                                 Antigua and Barbuda   NaN
13                                           Australia  12.3
14                                             Austria   3.0
15                                          Azerbaijan   8.9
16                                             Burundi   NaN
17                                             Belgium   3.7
18                                               Benin   NaN
19                                        Burkina Faso  47.9
20                                          Bangladesh  31.9
21                                            Bulgaria  13.2
22                                             Bahrain   NaN
23                                        Bahamas, The   NaN
24                              Bosnia and Herzegovina  10.0
25                                             Belarus   NaN
26                                              Belize   NaN
27                                             Bermuda   NaN
28                                             Bolivia   NaN
29                                              Brazil  23.5
30                                            Barbados   NaN
31                                   Brunei Darussalam   NaN
32                                              Bhutan   NaN
33                                            Botswana  50.8
34                            Central African Republic  81.3
35                                              Canada   5.8
36                      Central Europe and the Baltics   NaN
37                                         Switzerland   2.0
38                                     Channel Islands   NaN
39                                               Chile  17.9
40                                               China   NaN
41                                       Cote d'Ivoire   NaN
42                                            Cameroon  55.8
43                                    Congo, Dem. Rep.  69.2
44                                         Congo, Rep.  88.3
45                                            Colombia   NaN
46                                             Comoros   NaN
47                                          Cabo Verde  35.1
48                                          Costa Rica  15.3
49                              Caribbean small states   NaN
50                                                Cuba   NaN
51                                             Curacao   NaN
52                                      Cayman Islands   NaN
53                                              Cyprus   NaN
54                                      Czech Republic   4.2
55                                             Germany   3.4
56                                            Djibouti   NaN
57                                            Dominica   NaN
58                                             Denmark   5.0
59                                  Dominican Republic   NaN
60                                             Algeria  17.6
61         East Asia & Pacific (excluding high income)  10.8
62                          Early-demographic dividend   NaN
63                                 East Asia & Pacific  10.2
64       Europe & Central Asia (excluding high income)  16.3
65                               Europe & Central Asia  10.4
66                                             Ecuador  32.7
67                                    Egypt, Arab Rep.  27.8
68                                           Euro area   NaN
69                                             Eritrea   NaN
70                                               Spain   8.8
71                                             Estonia   7.9
72                                            Ethiopia  56.3
73                                      European Union   NaN
74            Fragile and conflict affected situations   NaN
75                                             Finland   8.0
76                                                Fiji  14.3
77                                              France   5.8
78                                       Faroe Islands   NaN
79                               Micronesia, Fed. Sts.   NaN
80                                               Gabon   NaN
81                                      United Kingdom   3.9
82                                             Georgia  39.7
83                                               Ghana  50.2
84                                           Gibraltar   NaN
85                                              Guinea  74.1
86                                         Gambia, The  56.0
87                                       Guinea-Bissau   NaN
88                                   Equatorial Guinea   NaN
89                                              Greece   8.6
90                                             Grenada   NaN
91                                           Greenland   NaN
92                                           Guatemala  49.7
93                                                Guam   NaN
94                                              Guyana   NaN
95                                         High income   7.6
96                                Hong Kong SAR, China   NaN
97                                            Honduras  45.6
98              Heavily indebted poor countries (HIPC)   NaN
99                                             Croatia  11.0
100                                              Haiti   NaN
101                                            Hungary   8.6
102                                          IBRD only   NaN
103                                   IDA & IBRD total   NaN
104                                          IDA total   NaN
105                                          IDA blend   NaN
106                                          Indonesia   6.2
107                                           IDA only   NaN
108                                        Isle of Man   NaN
109                                              India   NaN
110                                     Not classified   NaN
111                                            Ireland   8.3
112                                 Iran, Islamic Rep.  42.5
113                                               Iraq   NaN
114                                            Iceland   6.6
115                                             Israel  13.7
116                                              Italy   6.7
117                                            Jamaica   NaN
118                                             Jordan   NaN
119                                              Japan   3.4
120                                         Kazakhstan   2.3
121                                              Kenya  68.5
122                                    Kyrgyz Republic   7.0
123                                           Cambodia  44.8
124                                           Kiribati  40.9
125                                St. Kitts and Nevis   NaN
126                                        Korea, Rep.   5.1
127                                             Kuwait  12.2
128  Latin America & Caribbean (excluding high income)  32.2
129                                            Lao PDR  29.4
130                                            Lebanon   NaN
131                                            Liberia  80.6
132                                              Libya  37.4
133                                          St. Lucia   NaN
134                          Latin America & Caribbean  31.9
135       Least developed countries: UN classification   NaN
136                                         Low income  59.6
137                                      Liechtenstein   NaN
138                                          Sri Lanka   NaN
139                                Lower middle income  39.0
140                                Low & middle income   NaN
141                                            Lesotho  49.7
142                          Late-demographic dividend   NaN
143                                          Lithuania  11.3
144                                         Luxembourg   3.1
145                                             Latvia  10.2
146                                   Macao SAR, China   NaN
147                           St. Martin (French part)   NaN
148                                            Morocco  28.0
149                                             Monaco   NaN
150                                            Moldova  27.2
151                                         Madagascar   NaN
152                                           Maldives   NaN
153                         Middle East & North Africa  29.1
154                                             Mexico  26.1
155                                   Marshall Islands   NaN
156                                      Middle income   NaN
157                                    North Macedonia  17.7
158                                               Mali   NaN
159                                              Malta   4.3
160                                            Myanmar  22.2
161  Middle East & North Africa (excluding high inc...  30.9
162                                         Montenegro  13.5
163                                           Mongolia  26.2
164                           Northern Mariana Islands   NaN
165                                         Mozambique  71.1
166                                         Mauritania  39.8
167                                          Mauritius  24.2
168                                             Malawi  81.8
169                                           Malaysia  18.7
170                                      North America   7.6
171                                            Namibia  57.6
172                                      New Caledonia   NaN
173                                              Niger   NaN
174                                            Nigeria  57.7
175                                          Nicaragua   NaN
176                                        Netherlands   4.7
177                                             Norway   4.1
178                                              Nepal  36.4
179                                              Nauru   NaN
180                                        New Zealand  14.0
181                                       OECD members   NaN
182                                               Oman   NaN
183                                 Other small states   NaN
184                                           Pakistan   NaN
185                                             Panama   NaN
186                                               Peru  47.8
187                                        Philippines  42.7
188                                              Palau   NaN
189                                   Papua New Guinea   NaN
190                                             Poland   5.8
191                           Pre-demographic dividend   NaN
192                                        Puerto Rico   NaN
193                          Korea, Dem. People's Rep.   NaN
194                                           Portugal  11.5
195                                           Paraguay   NaN
196                                 West Bank and Gaza  26.3
197                        Pacific island small states   NaN
198                          Post-demographic dividend   NaN
199                                   French Polynesia   NaN
200                                              Qatar   NaN
201                                            Romania  13.9
202                                 Russian Federation   6.0
203                                             Rwanda   NaN
204                                         South Asia  37.4
205                                       Saudi Arabia   NaN
206                                              Sudan  49.4
207                                            Senegal  40.9
208                                          Singapore   4.5
209                                    Solomon Islands   NaN
210                                       Sierra Leone  83.9
211                                        El Salvador  47.1
212                                         San Marino   NaN
213                                            Somalia  79.1
214                                             Serbia  12.0
215         Sub-Saharan Africa (excluding high income)  59.5
216                                        South Sudan  84.8
217                                 Sub-Saharan Africa  59.5
218                                       Small states   NaN
219                              Sao Tome and Principe   NaN
220                                           Suriname   NaN
221                                    Slovak Republic   6.0
222                                           Slovenia   8.2
223                                             Sweden   5.3
224                                           Eswatini  64.1
225                          Sint Maarten (Dutch part)   NaN
226                                         Seychelles  14.7
227                               Syrian Arab Republic   NaN
228                           Turks and Caicos Islands   NaN
229                                               Chad   NaN
230         East Asia & Pacific (IDA & IBRD countries)   NaN
231       Europe & Central Asia (IDA & IBRD countries)   NaN
232                                               Togo   NaN
233                                           Thailand  29.8
234                                         Tajikistan   NaN
235                                       Turkmenistan   NaN
236  Latin America & the Caribbean (IDA & IBRD coun...   NaN
237                                        Timor-Leste   NaN
238  Middle East & North Africa (IDA & IBRD countries)   NaN
239                                              Tonga  23.2
240                            South Asia (IDA & IBRD)   NaN
241          Sub-Saharan Africa (IDA & IBRD countries)   NaN
242                                Trinidad and Tobago   NaN
243                                            Tunisia  25.1
244                                             Turkey   NaN
245                                             Tuvalu   NaN
246                                           Tanzania  56.4
247                                             Uganda  69.2
248                                            Ukraine   NaN
249                                Upper middle income  17.3
250                                            Uruguay  23.5
251                                      United States   8.0
252                                         Uzbekistan  19.7
253                     St. Vincent and the Grenadines   NaN
254                                      Venezuela, RB   NaN
255                             British Virgin Islands   NaN
256                              Virgin Islands (U.S.)   NaN
257                                            Vietnam   6.5
258                                            Vanuatu  23.3
259                                              World  27.6
260                                              Samoa  23.6
261                                             Kosovo   NaN
262                                        Yemen, Rep.   NaN
263                                       South Africa  44.9
264                                             Zambia  51.4
265                                           Zimbabwe  69.8

In [223]:
# 'Prevalence of moderate or severe food insecurity in the population (%)'
FI.columns = ["Country Name", '2019_Prevalence of moderate or severe food insecurity in the population (%)']

In [224]:
FI.head()

,Country Name,2019_Prevalence of moderate or severe food insecurity in the population (%)
0,Aruba,NaN
1,Africa Eastern and Southern,NaN
2,Afghanistan,63.1
3,Africa Western and Central,NaN
4,Angola,73.5

## Creating Country Poverty Dataframe - PR dataframe

In [258]:
PR =pd.read_csv("Country Poverty Rates.csv",header = 4)
PR.shape

(7714, 65)

In [259]:
# pd.set_option('display.max_columns', None)
# PR.head(100)

In [260]:
# pd.set_option("max_rows", None)
# PR

In [261]:
PR['Indicator Name'].unique()

array(['Annualized average growth rate in per capita real survey mean consumption or income, total population (%)',
       'Survey mean consumption or income per capita, total population (2011 PPP $ per day)',
       'Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)',
       'Survey mean consumption or income per capita, bottom 40% of population (2011 PPP $ per day)',
       'Poverty gap at $5.50 a day (2011 PPP) (%)',
       'Poverty headcount ratio at $5.50 a day (2011 PPP) (% of population)',
       'Poverty headcount ratio at national poverty lines (% of population)',
       'Multidimensional poverty index (scale 0-1)',
       'Multidimensional poverty headcount ratio, male (% of male population)',
       'Multidimensional poverty intensity (average share of deprivations experienced by the poor)',
       'Multidimensional poverty headcount ratio, household (% of total households)',
       'Multidimensional poverty headcount ratio, female (% of female population)',
       'Multidimensional poverty index, children (population ages 0-17) (scale 0-1)',
       'Multidimensional poverty headcount ratio, children (% of population ages 0-17)',
       'Multidimensional poverty headcount ratio (% of total population)',
       'Poverty gap at $3.20 a day (2011 PPP) (%)',
       'Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)',
       'Gini index (World Bank estimate)',
       'Poverty gap at $1.90 a day (2011 PPP) (%)',
       'Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)',
       'Income share held by lowest 20%',
       'Income share held by lowest 10%',
       'Proportion of people living below 50 percent of median income (%)',
       'Income share held by highest 10%',
       'Income share held by highest 20%',
       'Income share held by fourth 20%',
       'Income share held by third 20%',
       'Income share held by second 20%',
       'Population living in slums (% of urban population)'], dtype=object)

In [262]:
# Selecting the indicator tu use for analysis: 
# 'Poverty headcount ratio at national poverty lines (% of population)' - using Indicator https://data.worldbank.org/indicator/SI.POV.NAHC?locations=CO&view=map&year_high_desc=true
PR = PR[(PR['Indicator Name'] == 'Poverty headcount ratio at national poverty lines (% of population)')][['Country Name','2017','2018','2019','2020']]

In [263]:
print(PR.shape)
PR.head(3)

(266, 5)

                   Country Name  2017  2018  2019  2020
6                         Aruba   NaN   NaN   NaN   NaN
35  Africa Eastern and Southern   NaN   NaN   NaN   NaN
64                  Afghanistan   NaN   NaN   NaN   NaN

In [264]:
# Setting index to country name to facilitate selection of most recent year value from dataset
PR = PR.set_index('Country Name')

In [266]:
PR.head(3)

                             2017  2018  2019  2020
Country Name
Aruba                         NaN   NaN   NaN   NaN
Africa Eastern and Southern   NaN   NaN   NaN   NaN
Afghanistan                   NaN   NaN   NaN   NaN

In [267]:
# using last non nan value from the years between (2017-2020)
PR['Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)'] = PR.ffill(axis=1).iloc[:, -1]
PR.head(3)

,2017,2018,2019,2020,Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)
Country Name,,,,,
Aruba,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,NaN

In [268]:
# Resetting index
PR = PR.reset_index()

In [269]:
PR.head(2)

,Country Name,2017,2018,2019,2020,Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)
0,Aruba,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN

In [270]:
# Selecting only columns to be used in final dataframe (to merge with regions data)
PR = PR.filter(['Country Name', 'Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)'], axis=1)
PR.head()

,Country Name,Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)
0,Aruba,NaN
1,Africa Eastern and Southern,NaN
2,Afghanistan,NaN
3,Africa Western and Central,NaN
4,Angola,32.3

## Creating Country Maternal Mortality Rate Dataframe -  mmr dataframe

In [271]:
mmr =pd.read_csv("Country Maternal Mortality Rates.csv",header = 4)
mmr.shape

(266, 65)

In [272]:
mmr.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype='object')

In [273]:
# Selecting feature name
mmr['Indicator Name'].unique()

array(['Maternal mortality ratio (modeled estimate, per 100,000 live births)'],
      dtype=object)

In [274]:
# latest values are already set to 2017
mmr = mmr.filter(['Country Name','2017'], axis=1)
mmr

                                          Country Name    2017
0                                                Aruba     NaN
1                          Africa Eastern and Southern   398.0
2                                          Afghanistan   638.0
3                           Africa Western and Central   717.0
4                                               Angola   241.0
5                                              Albania    15.0
6                                              Andorra     NaN
7                                           Arab World   149.0
8                                 United Arab Emirates     3.0
9                                            Argentina    39.0
10                                             Armenia    26.0
11                                      American Samoa     NaN
12                                 Antigua and Barbuda    42.0
13                                           Australia     6.0
14                                             Austria     5.0
15                                          Azerbaijan    26.0
16                                             Burundi   548.0
17                                             Belgium     5.0
18                                               Benin   397.0
19                                        Burkina Faso   320.0
20                                          Bangladesh   173.0
21                                            Bulgaria    10.0
22                                             Bahrain    14.0
23                                        Bahamas, The    70.0
24                              Bosnia and Herzegovina    10.0
25                                             Belarus     2.0
26                                              Belize    36.0
27                                             Bermuda     NaN
28                                             Bolivia   155.0
29                                              Brazil    60.0
30                                            Barbados    27.0
31                                   Brunei Darussalam    31.0
32                                              Bhutan   183.0
33                                            Botswana   144.0
34                            Central African Republic   829.0
35                                              Canada    10.0
36                      Central Europe and the Baltics     8.0
37                                         Switzerland     5.0
38                                     Channel Islands     NaN
39                                               Chile    13.0
40                                               China    29.0
41                                       Cote d'Ivoire   617.0
42                                            Cameroon   529.0
43                                    Congo, Dem. Rep.   473.0
44                                         Congo, Rep.   378.0
45                                            Colombia    83.0
46                                             Comoros   273.0
47                                          Cabo Verde    58.0
48                                          Costa Rica    27.0
49                              Caribbean small states    88.0
50                                                Cuba    36.0
51                                             Curacao     NaN
52                                      Cayman Islands     NaN
53                                              Cyprus     6.0
54                                      Czech Republic     3.0
55                                             Germany     7.0
56                                            Djibouti   248.0
57                                            Dominica     NaN
58                                             Denmark     4.0
59                                  Dominican Republic    95.0
60                                             Algeria   112.0
61         East Asia & Pacific (excluding high income)    73.0
62                          Early-demographic dividend   147.0
63                                 East Asia & Pacific    69.0
64       Europe & Central Asia (excluding high income)    19.0
65                               Europe & Central Asia    13.0
66                                             Ecuador    59.0
67                                    Egypt, Arab Rep.    37.0
68                                           Euro area     5.0
69                                             Eritrea   480.0
70                                               Spain     4.0
71                                             Estonia     9.0
72                                            Ethiopia   401.0
73                                      European Union     6.0
74            Fragile and conflict affected situations   546.0
75                                             Finland     3.0
76                                                Fiji    34.0
77                                              France     8.0
78                                       Faroe Islands     NaN
79                               Micronesia, Fed. Sts.    88.0
80                                               Gabon   252.0
81                                      United Kingdom     7.0
82                                             Georgia    25.0
83                                               Ghana   308.0
84                                           Gibraltar     NaN
85                                              Guinea   576.0
86                                         Gambia, The   597.0
87                                       Guinea-Bissau   667.0
88                                   Equatorial Guinea   301.0
89                                              Greece     3.0
90                                             Grenada    25.0
91                                           Greenland     NaN
92                                           Guatemala    95.0
93                                                Guam     NaN
94                                              Guyana   169.0
95                                         High income    11.0
96                                Hong Kong SAR, China     NaN
97                                            Honduras    65.0
98              Heavily indebted poor countries (HIPC)   462.0
99                                             Croatia     8.0
100                                              Haiti   480.0
101                                            Hungary    12.0
102                                          IBRD only    89.0
103                                   IDA & IBRD total   230.0
104                                          IDA total   445.0
105                                          IDA blend   513.0
106                                          Indonesia   177.0
107                                           IDA only   410.0
108                                        Isle of Man     NaN
109                                              India   145.0
110                                     Not classified     NaN
111                                            Ireland     5.0
112                                 Iran, Islamic Rep.    16.0
113                                               Iraq    79.0
114                                            Iceland     4.0
115                                             Israel     3.0
116                                              Italy     2.0
117                                            Jamaica    80.0
118                                             Jordan    46.0
119                                              Japan     5.0
120                                         Kazakhstan    10.0
121                                              Kenya   342.0
122                                    Kyrgyz Republic    60.0
123                                           Cambodia   160.0
124                                           Kiribati    92.0
125                                St. Kitts and Nevis     NaN
126                                        Korea, Rep.    11.0
127                                             Kuwait    12.0
128  Latin America & Caribbean (excluding high income)    73.0
129                                            Lao PDR   185.0
130                                            Lebanon    29.0
131                                            Liberia   661.0
132                                              Libya    72.0
133                                          St. Lucia   117.0
134                          Latin America & Caribbean    74.0
135       Least developed countries: UN classification   415.0
136                                         Low income   460.0
137                                      Liechtenstein     NaN
138                                          Sri Lanka    36.0
139                                Lower middle income   253.0
140                                Low & middle income   231.0
141                                            Lesotho   544.0
142                          Late-demographic dividend    34.0
143                                          Lithuania     8.0
144                                         Luxembourg     5.0
145                                             Latvia    19.0
146                                   Macao SAR, China     NaN
147                           St. Martin (French part)     NaN
148                                            Morocco    70.0
149                                             Monaco     NaN
150                                            Moldova    19.0
151                                         Madagascar   335.0
152                                           Maldives    53.0
153                         Middle East & North Africa    57.0
154                                             Mexico    33.0
155                                   Marshall Islands     NaN
156                                      Middle income   183.0
157                                    North Macedonia     7.0
158                                               Mali   562.0
159                                              Malta     6.0
160                                            Myanmar   250.0
161  Middle East & North Africa (excluding high inc...    62.0
162                                         Montenegro     6.0
163                                           Mongolia    45.0
164                           Northern Mariana Islands     NaN
165                                         Mozambique   289.0
166                                         Mauritania   766.0
167                                          Mauritius    61.0
168                                             Malawi   349.0
169                                           Malaysia    29.0
170                                      North America    18.0
171                                            Namibia   195.0
172                                      New Caledonia     NaN
173                                              Niger   509.0
174                                            Nigeria   917.0
175                                          Nicaragua    98.0
176                                        Netherlands     5.0
177                                             Norway     2.0
178                                              Nepal   186.0
179                                              Nauru     NaN
180                                        New Zealand     9.0
181                                       OECD members    18.0
182                                               Oman    19.0
183                                 Other small states   303.0
184                                           Pakistan   140.0
185                                             Panama    52.0
186                                               Peru    88.0
187                                        Philippines   121.0
188                                              Palau     NaN
189                                   Papua New Guinea   145.0
190                                             Poland     2.0
191                           Pre-demographic dividend   563.0
192                                        Puerto Rico    21.0
193                          Korea, Dem. People's Rep.    89.0
194                                           Portugal     8.0
195                                           Paraguay   129.0
196                                 West Bank and Gaza    27.0
197                        Pacific island small states    70.0
198                          Post-demographic dividend    11.0
199                                   French Polynesia     NaN
200                                              Qatar     9.0
201                                            Romania    19.0
202                                 Russian Federation    17.0
203                                             Rwanda   248.0
204                                         South Asia   163.0
205                                       Saudi Arabia    17.0
206                                              Sudan   295.0
207                                            Senegal   315.0
208                                          Singapore     8.0
209                                    Solomon Islands   104.0
210                                       Sierra Leone  1120.0
211                                        El Salvador    46.0
212                                         San Marino     NaN
213                                            Somalia   829.0
214                                             Serbia    12.0
215         Sub-Saharan Africa (excluding high income)   534.0
216                                        South Sudan  1150.0
217                                 Sub-Saharan Africa   534.0
218                                       Small states   259.0
219                              Sao Tome and Principe   130.0
220                                           Suriname   120.0
221                                    Slovak Republic     5.0
222                                           Slovenia     7.0
223                                             Sweden     4.0
224                                           Eswatini   437.0
225                          Sint Maarten (Dutch part)     NaN
226                                         Seychelles    53.0
227                               Syrian Arab Republic    31.0
228                           Turks and Caicos Islands     NaN
229                                               Chad  1140.0
230         East Asia & Pacific (IDA & IBRD countries)    73.0
231       Europe & Central Asia (IDA & IBRD countries)    18.0
232                                               Togo   396.0
233                                           Thailand    37.0
234                                         Tajikistan    17.0
235                                       Turkmenistan     7.0
236  Latin America & the Caribbean (IDA & IBRD coun...    75.0
237                                        Timor-Leste   142.0
238  Middle East & North Africa (IDA & IBRD countries)    63.0
239                                              Tonga    52.0
240                            South Asia (IDA & IBRD)   163.0
241          Sub-Saharan Africa (IDA & IBRD countries)   534.0
242                                Trinidad and Tobago    67.0
243                                            Tunisia    43.0
244                                             Turkey    17.0
245                                             Tuvalu     NaN
246                                           Tanzania   524.0
247                                             Uganda   375.0
248                                            Ukraine    19.0
249                                Upper middle income    41.0
250                                            Uruguay    17.0
251                                      United States    19.0
252                                         Uzbekistan    29.0
253                     St. Vincent and the Grenadines    68.0
254                                      Venezuela, RB   125.0
255                             British Virgin Islands     NaN
256                              Virgin Islands (U.S.)     NaN
257                                            Vietnam    43.0
258                                            Vanuatu    72.0
259                                              World   211.0
260                                              Samoa    43.0
261                                             Kosovo     NaN
262                                        Yemen, Rep.   164.0
263                                       South Africa   119.0
264                                             Zambia   213.0
265                                           Zimbabwe   458.0

In [275]:
# Changing Column Name
mmr.columns = ["Country Name", '2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)']

In [276]:
print(mmr.shape)
mmr.head(3)

(266, 2)

,Country Name,"2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)"
0,Aruba,NaN
1,Africa Eastern and Southern,398.0
2,Afghanistan,638.0

In [278]:
# Checking shape of dataframes
print(FI.shape)
print(PR.shape)
print(mmr.shape)
print(data.shape)

(266, 2)
(266, 2)
(266, 2)
(125306, 156)

In [279]:
# Merging Food Insecurity and Poverty Rate Dataframes
FI_PR = pd.merge(FI,PR, how='left', left_on='Country Name', right_on='Country Name' )
FI_PR.head()

,Country Name,2019_Prevalence of moderate or severe food insecurity in the population (%),Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)
0,Aruba,NaN,NaN
1,Africa Eastern and Southern,NaN,NaN
2,Afghanistan,63.1,NaN
3,Africa Western and Central,NaN,NaN
4,Angola,73.5,32.3

In [280]:
# Merging Food Insecurity, Poverty Rate, and Maternal Mortality Rate into one dataframe
FI_PR_mmr = pd.merge(FI_PR, mmr, how='left', left_on='Country Name', right_on='Country Name')
FI_PR_mmr.head()

,Country Name,2019_Prevalence of moderate or severe food insecurity in the population (%),Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population),"2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)"
0,Aruba,NaN,NaN,NaN
1,Africa Eastern and Southern,NaN,NaN,398.0
2,Afghanistan,63.1,NaN,638.0
3,Africa Western and Central,NaN,NaN,717.0
4,Angola,73.5,32.3,241.0

## Adding Food Insecurity, Poverty Rate and Maternal Mortality to survey Dataframe

In [315]:
# Merging FI, PR and mmr with our regions_survey dataframe, and creating new dataframe
data2 = pd.merge(data, FI_PR_mmr, how="left", left_on="Country", right_on="Country Name")

In [316]:
print(data2.shape)
data2.head()

(125306, 160)

,ID,answered_all,Duration..in.seconds.,RecordedDate,UserLanguage,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Country Income Level,Region,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Dem_isolation,Dem_isolation_adults,Dem_isolation_kids,AD_gain,AD_loss,AD_check,Scale_PSS10_UCLA_1,Scale_PSS10_UCLA_2,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_4,Scale_PSS10_UCLA_5,Scale_PSS10_UCLA_6,Scale_PSS10_UCLA_7,Scale_PSS10_UCLA_8,Scale_PSS10_UCLA_9,Scale_PSS10_UCLA_10,Scale_SLON_1,Scale_SLON_2,Scale_SLON_3,OECD_people_1,OECD_people_2,OECD_insititutions_1,OECD_insititutions_2,OECD_insititutions_3,OECD_insititutions_4,OECD_insititutions_5,OECD_insititutions_6,Corona_concerns_1,Corona_concerns_2,Corona_concerns_3,Corona_concerns_4,Corona_concerns_5,Trust_countrymeasure,Compliance_1,Compliance_2,Compliance_3,Compliance_4,Compliance_5,Compliance_6,born_92,experience_war,experience_war_TXT,war_injury,loss_during_war,time_spent_in_war,time_spent_in_war_TXT,Scale_UCLA_TRI_1,Scale_UCLA_TRI_2,Scale_UCLA_TRI_3,Scale_UCLA_TRI_4,PS_PTSD_1,PS_PTSD_2,PS_PTSD_3,PS_PTSD_4,PS_PTSD_5,BFF_15_1,BFF_15_2,BFF_15_3,BFF_15_4,BFF_15_5,BFF_15_6,BFF_15_7,BFF_15_8,BFF_15_9,BFF_15_10,BFF_15_11,BFF_15_12,BFF_15_13,BFF_15_14,BFF_15_15,Expl_Distress_1,Expl_Distress_2,Expl_Distress_3,Expl_Distress_4,Expl_Distress_5,Expl_Distress_6,Expl_Distress_7,Expl_Distress_8,Expl_Distress_9,Expl_Distress_10,Expl_Distress_11,Expl_Distress_12,Expl_Distress_13,Expl_Distress_14,Expl_Distress_15,Expl_Distress_16,Expl_Distress_17,Expl_Distress_18,Expl_Distress_19,Expl_Distress_20,Expl_Distress_21,Expl_Distress_22,Expl_Distress_23,Expl_Distress_24,Expl_Distress_txt,SPS_1,SPS_2,SPS_3,SPS_4,SPS_5,SPS_6,SPS_7,SPS_8,SPS_9,SPS_10,Expl_Coping_1,Expl_Coping_2,Expl_Coping_3,Expl_Coping_4,Expl_Coping_5,Expl_Coping_6,Expl_Coping_7,Expl_Coping_8,Expl_Coping_9,Expl_Coping_10,Expl_Coping_11,Expl_Coping_12,Expl_Coping_13,Expl_Coping_14,Expl_Coping_15,Expl_Coping_16,Expl_coping_txt,Expl_media_1,Expl_media_2,Expl_media_3,Expl_media_4,Expl_media_5,Expl_media_6,Final_open,PSS10_avg,SLON3_avg,neu,ext,ope,agr,con,SPS_avg,Scale_UCLA_TRI_avg,Country Name,2019_Prevalence of moderate or severe food insecurity in the population (%),Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population),"2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)"
0,4069,No,856,5/12/20 1:34,FA,30,Male,"College degree, bachelor, master",Up to 6 years of school,Full time employed,Afghanistan,Low Income,South Asia,yes,<U+06A9><U+0627><U+0628><U+0644>,Married/cohabiting,3.0,Yes,Life carries on with minor changes,4.0,0.0,NaN,Â· If Program D is adopted there is 1/3 probabi...,No,3.0,1.0,3.0,5.0,4.0,2.0,4.0,4.0,3.0,3.0,1.0,1.0,2.0,5.0,6.0,NaN,1.0,2.0,1.0,8.0,1.0,2.0,4.0,3.0,5.0,4.0,0.0,5.0,4.0,4.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,5.0,6.0,6.0,1.0,6.0,6.0,6.0,2.0,4.0,5.0,6.0,1.0,5.0,6.0,NaN,4.0,NaN,NaN,1.0,3.0,NaN,NaN,6.0,NaN,NaN,NaN,5.0,2.0,NaN,NaN,4.0,2.0,NaN,2.0,1.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2,1.333333,2.333333,6.000000,6.0,4.666667,5.666667,NaN,NaN,Afghanistan,63.1,NaN,638.0
1,4460,No,89,5/12/20 0:28,KO,26,Other/would rather not say,PhD/Doctorate,PhD/Doctorate,Student,Afghanistan,Low Income,South Asia,yes,<U+3147><U+314E>,Other or would rather not say,0.0,No,Life carries on as usual,0.0,0.0,NaN,Â· If Program C is adopted 400 people will die.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,63.1,NaN,638.0
2,9383,No,305,4/30/20 0:53,EN,26,Male,PhD/Doctorate,College degree,Full time employed,Afghanistan,Low Income,South Asia,yes,NaN,NaN,NaN,NaN,Isolated,NaN,NaN,"Â· If Program B is adopted, there is 1/3 probab...",NaN,No,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,63.1,NaN,638.0
3,10249,No,48,4/27/20 7:32,HR,18,Female,"College degree, bachelor, master",PhD/Doctorate,Full time employed,Afghanistan,Low Income,South Asia,yes,Grad Zagreb,Single,0.0,Yes,Life carries on with minor changes,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,63.1,NaN,638.0
4,12234,Yes,4443,4/20/20 19:46,FA,22,Female,"Some College, short continuing education or eq...",None,Student,Afghanistan,Low Income,South Asia,yes,<U+06A9><U+0627><U+0628><U+0644>,Single,0.0,No,Life carries on with minor changes,4.0,0.0,"Â· If Program A is adopted, 200 people will be ...",NaN,Yes,4.0,2.0,3.0,3.0,3.0,2.0,4.0,2.0,3.0,2.0,3.0,3.0,3.0,5.0,9.0,1.0,2.0,1.0,1.0,5.0,3.0,5.0,6.0,6.0,6.0,6.0,5.0,6.0,6.0,6.0,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,3.0,6.0,5.0,1.0,5.0,4.0,6.0,2.0,4.0,5.0,5.0,1.0,6.0,4.0,5.0,6.0,5.0,5.0,5.0,6.0,4.0,99.0,6.0,5.0,6.0,5.0,5.0,6.0,6.0,1.0,5.0,4.0,2.0,2.0,3.0,6.0,4.0,NaN,5.0,4.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,2.0,2.0,3.0,5.0,2.0,6.0,3.0,3.0,6.0,4.0,NaN,3.0,4.0,4.0,5.0,5.0,5.0,<U+0627><U+06CC><U+0646> <U+0648><U+06CC><U+06...,2.8,3.000000,3.666667,5.666667,5.0,4.666667,5.666667,4.6,NaN,Afghanistan,63.1,NaN,638.0

In [317]:
data2 = data2.drop(['Country Name'], axis=1)
data2.head(2)

,ID,answered_all,Duration..in.seconds.,RecordedDate,UserLanguage,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Country Income Level,Region,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Dem_isolation,Dem_isolation_adults,Dem_isolation_kids,AD_gain,AD_loss,AD_check,Scale_PSS10_UCLA_1,Scale_PSS10_UCLA_2,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_4,Scale_PSS10_UCLA_5,Scale_PSS10_UCLA_6,Scale_PSS10_UCLA_7,Scale_PSS10_UCLA_8,Scale_PSS10_UCLA_9,Scale_PSS10_UCLA_10,Scale_SLON_1,Scale_SLON_2,Scale_SLON_3,OECD_people_1,OECD_people_2,OECD_insititutions_1,OECD_insititutions_2,OECD_insititutions_3,OECD_insititutions_4,OECD_insititutions_5,OECD_insititutions_6,Corona_concerns_1,Corona_concerns_2,Corona_concerns_3,Corona_concerns_4,Corona_concerns_5,Trust_countrymeasure,Compliance_1,Compliance_2,Compliance_3,Compliance_4,Compliance_5,Compliance_6,born_92,experience_war,experience_war_TXT,war_injury,loss_during_war,time_spent_in_war,time_spent_in_war_TXT,Scale_UCLA_TRI_1,Scale_UCLA_TRI_2,Scale_UCLA_TRI_3,Scale_UCLA_TRI_4,PS_PTSD_1,PS_PTSD_2,PS_PTSD_3,PS_PTSD_4,PS_PTSD_5,BFF_15_1,BFF_15_2,BFF_15_3,BFF_15_4,BFF_15_5,BFF_15_6,BFF_15_7,BFF_15_8,BFF_15_9,BFF_15_10,BFF_15_11,BFF_15_12,BFF_15_13,BFF_15_14,BFF_15_15,Expl_Distress_1,Expl_Distress_2,Expl_Distress_3,Expl_Distress_4,Expl_Distress_5,Expl_Distress_6,Expl_Distress_7,Expl_Distress_8,Expl_Distress_9,Expl_Distress_10,Expl_Distress_11,Expl_Distress_12,Expl_Distress_13,Expl_Distress_14,Expl_Distress_15,Expl_Distress_16,Expl_Distress_17,Expl_Distress_18,Expl_Distress_19,Expl_Distress_20,Expl_Distress_21,Expl_Distress_22,Expl_Distress_23,Expl_Distress_24,Expl_Distress_txt,SPS_1,SPS_2,SPS_3,SPS_4,SPS_5,SPS_6,SPS_7,SPS_8,SPS_9,SPS_10,Expl_Coping_1,Expl_Coping_2,Expl_Coping_3,Expl_Coping_4,Expl_Coping_5,Expl_Coping_6,Expl_Coping_7,Expl_Coping_8,Expl_Coping_9,Expl_Coping_10,Expl_Coping_11,Expl_Coping_12,Expl_Coping_13,Expl_Coping_14,Expl_Coping_15,Expl_Coping_16,Expl_coping_txt,Expl_media_1,Expl_media_2,Expl_media_3,Expl_media_4,Expl_media_5,Expl_media_6,Final_open,PSS10_avg,SLON3_avg,neu,ext,ope,agr,con,SPS_avg,Scale_UCLA_TRI_avg,2019_Prevalence of moderate or severe food insecurity in the population (%),Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population),"2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)"
0,4069,No,856,5/12/20 1:34,FA,30,Male,"College degree, bachelor, master",Up to 6 years of school,Full time employed,Afghanistan,Low Income,South Asia,yes,<U+06A9><U+0627><U+0628><U+0644>,Married/cohabiting,3.0,Yes,Life carries on with minor changes,4.0,0.0,NaN,Â· If Program D is adopted there is 1/3 probabi...,No,3.0,1.0,3.0,5.0,4.0,2.0,4.0,4.0,3.0,3.0,1.0,1.0,2.0,5.0,6.0,NaN,1.0,2.0,1.0,8.0,1.0,2.0,4.0,3.0,5.0,4.0,0.0,5.0,4.0,4.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,5.0,6.0,6.0,1.0,6.0,6.0,6.0,2.0,4.0,5.0,6.0,1.0,5.0,6.0,NaN,4.0,NaN,NaN,1.0,3.0,NaN,NaN,6.0,NaN,NaN,NaN,5.0,2.0,NaN,NaN,4.0,2.0,NaN,2.0,1.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2,1.333333,2.333333,6.0,6.0,4.666667,5.666667,NaN,NaN,63.1,NaN,638.0
1,4460,No,89,5/12/20 0:28,KO,26,Other/would rather not say,PhD/Doctorate,PhD/Doctorate,Student,Afghanistan,Low Income,South Asia,yes,<U+3147><U+314E>,Other or would rather not say,0.0,No,Life carries on as usual,0.0,0.0,NaN,Â· If Program C is adopted 400 people will die.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.1,NaN,638.0

In [318]:
# Comparing shape of dataframes before and after merge
print(data.shape)
print(data2.shape)

(125306, 156)
(125306, 159)

In [319]:
# list(data2.columns.values)

In [321]:
# Moving column positions to have demographic information grouped together
cols = data2.columns.tolist()
column_to_move = "2019_Prevalence of moderate or severe food insecurity in the population (%)"
new_position = 13

cols.insert(new_position, cols.pop(cols.index(column_to_move)))
data2 = data2[cols]

In [322]:
# Moving column positions to have demographic information grouped together
cols = data2.columns.tolist()
column_to_move = "Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population)"
new_position = 14

cols.insert(new_position, cols.pop(cols.index(column_to_move)))
data2 = data2[cols]

In [323]:
cols = data2.columns.tolist()
column_to_move = "2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)"
new_position = 15

cols.insert(new_position, cols.pop(cols.index(column_to_move)))
data2 = data2[cols]

In [324]:
data2.head()

,ID,answered_all,Duration..in.seconds.,RecordedDate,UserLanguage,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Country Income Level,Region,2019_Prevalence of moderate or severe food insecurity in the population (%),Most recent year value (2017-2020)_Poverty headcount ratio at national poverty lines (% of population),"2017_Maternal mortality ratio (modeled estimate, per 100,000 live births)",Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Dem_isolation,Dem_isolation_adults,Dem_isolation_kids,AD_gain,AD_loss,AD_check,Scale_PSS10_UCLA_1,Scale_PSS10_UCLA_2,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_4,Scale_PSS10_UCLA_5,Scale_PSS10_UCLA_6,Scale_PSS10_UCLA_7,Scale_PSS10_UCLA_8,Scale_PSS10_UCLA_9,Scale_PSS10_UCLA_10,Scale_SLON_1,Scale_SLON_2,Scale_SLON_3,OECD_people_1,OECD_people_2,OECD_insititutions_1,OECD_insititutions_2,OECD_insititutions_3,OECD_insititutions_4,OECD_insititutions_5,OECD_insititutions_6,Corona_concerns_1,Corona_concerns_2,Corona_concerns_3,Corona_concerns_4,Corona_concerns_5,Trust_countrymeasure,Compliance_1,Compliance_2,Compliance_3,Compliance_4,Compliance_5,Compliance_6,born_92,experience_war,experience_war_TXT,war_injury,loss_during_war,time_spent_in_war,time_spent_in_war_TXT,Scale_UCLA_TRI_1,Scale_UCLA_TRI_2,Scale_UCLA_TRI_3,Scale_UCLA_TRI_4,PS_PTSD_1,PS_PTSD_2,PS_PTSD_3,PS_PTSD_4,PS_PTSD_5,BFF_15_1,BFF_15_2,BFF_15_3,BFF_15_4,BFF_15_5,BFF_15_6,BFF_15_7,BFF_15_8,BFF_15_9,BFF_15_10,BFF_15_11,BFF_15_12,BFF_15_13,BFF_15_14,BFF_15_15,Expl_Distress_1,Expl_Distress_2,Expl_Distress_3,Expl_Distress_4,Expl_Distress_5,Expl_Distress_6,Expl_Distress_7,Expl_Distress_8,Expl_Distress_9,Expl_Distress_10,Expl_Distress_11,Expl_Distress_12,Expl_Distress_13,Expl_Distress_14,Expl_Distress_15,Expl_Distress_16,Expl_Distress_17,Expl_Distress_18,Expl_Distress_19,Expl_Distress_20,Expl_Distress_21,Expl_Distress_22,Expl_Distress_23,Expl_Distress_24,Expl_Distress_txt,SPS_1,SPS_2,SPS_3,SPS_4,SPS_5,SPS_6,SPS_7,SPS_8,SPS_9,SPS_10,Expl_Coping_1,Expl_Coping_2,Expl_Coping_3,Expl_Coping_4,Expl_Coping_5,Expl_Coping_6,Expl_Coping_7,Expl_Coping_8,Expl_Coping_9,Expl_Coping_10,Expl_Coping_11,Expl_Coping_12,Expl_Coping_13,Expl_Coping_14,Expl_Coping_15,Expl_Coping_16,Expl_coping_txt,Expl_media_1,Expl_media_2,Expl_media_3,Expl_media_4,Expl_media_5,Expl_media_6,Final_open,PSS10_avg,SLON3_avg,neu,ext,ope,agr,con,SPS_avg,Scale_UCLA_TRI_avg
0,4069,No,856,5/12/20 1:34,FA,30,Male,"College degree, bachelor, master",Up to 6 years of school,Full time employed,Afghanistan,Low Income,South Asia,63.1,NaN,638.0,yes,<U+06A9><U+0627><U+0628><U+0644>,Married/cohabiting,3.0,Yes,Life carries on with minor changes,4.0,0.0,NaN,Â· If Program D is adopted there is 1/3 probabi...,No,3.0,1.0,3.0,5.0,4.0,2.0,4.0,4.0,3.0,3.0,1.0,1.0,2.0,5.0,6.0,NaN,1.0,2.0,1.0,8.0,1.0,2.0,4.0,3.0,5.0,4.0,0.0,5.0,4.0,4.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,5.0,6.0,6.0,1.0,6.0,6.0,6.0,2.0,4.0,5.0,6.0,1.0,5.0,6.0,NaN,4.0,NaN,NaN,1.0,3.0,NaN,NaN,6.0,NaN,NaN,NaN,5.0,2.0,NaN,NaN,4.0,2.0,NaN,2.0,1.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.2,1.333333,2.333333,6.000000,6.0,4.666667,5.666667,NaN,NaN
1,4460,No,89,5/12/20 0:28,KO,26,Other/would rather not say,PhD/Doctorate,PhD/Doctorate,Student,Afghanistan,Low Income,South Asia,63.1,NaN,638.0,yes,<U+3147><U+314E>,Other or would rather not say,0.0,No,Life carries on as usual,0.0,0.0,NaN,Â· If Program C is adopted 400 people will die.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9383,No,305,4/30/20 0:53,EN,26,Male,PhD/Doctorate,College degree,Full time employed,Afghanistan,Low Income,South Asia,63.1,NaN,638.0,yes,NaN,NaN,NaN,NaN,Isolated,NaN,NaN,"Â· If Program B is adopted, there is 1/3 probab...",NaN,No,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10249,No,48,4/27/20 7:32,HR,18,Female,"College degree, bachelor, master",PhD/Doctorate,Full time employed,Afghanistan,Low Income,South Asia,63.1,NaN,638.0,yes,Grad Zagreb,Single,0.0,Yes,Life carries on with minor changes,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12234,Yes,4443,4/20/20 19:46,FA,22,Female,"Some College, short continuing education or eq...",None,Student,Afghanistan,Low Income,South Asia,63.1,NaN,638.0,yes,<U+06A9><U+0627><U+0628><U+0644>,Single,0.0,No,Life carries on with minor changes,4.0,0.0,"Â· If Program A is adopted, 200 people will be ...",NaN,Yes,4.0,2.0,3.0,3.0,3.0,2.0,4.0,2.0,3.0,2.0,3.0,3.0,3.0,5.0,9.0,1.0,2.0,1.0,1.0,5.0,3.0,5.0,6.0,6.0,6.0,6.0,5.0,6.0,6.0,6.0,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,3.0,6.0,5.0,1.0,5.0,4.0,6.0,2.0,4.0,5.0,5.0,1.0,6.0,4.0,5.0,6.0,5.0,5.0,5.0,6.0,4.0,99.0,6.0,5.0,6.0,5.0,5.0,6.0,6.0,1.0,5.0,4.0,2.0,2.0,3.0,6.0,4.0,NaN,5.0,4.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,2.0,2.0,3.0,5.0,2.0,6.0,3.0,3.0,6.0,4.0,NaN,3.0,4.0,4.0,5.0,5.0,5.0,<U+0627><U+06CC><U+0646> <U+0648><U+06CC><U+06...,2.8,3.000000,3.666667,5.666667,5.0,4.666667,5.666667,4.6,NaN

In [327]:
data2.to_csv('COVIDistress_data_with_fi_pr_mmr.csv')